### ISSUE TITLE
Webhook functionality doesn't seem to be working

### ISSUE THREAD

**Issue by David-Moreira** [David-Moreira/JellyseerrSync#4]
Hey man, just thought I'd let you know the Webhook functionality doesn't seem to be working... If I go to /syncdeleted/movies then it works fine. But if I delete a movie from my Jellyfin library and then update Radarr, when it gets marked as "missing" nothing really happens. Even if I delete the movie from Radarr nothing happens.

_Originally posted by @bleak117 in https://github.com/David-Moreira/JellyseerrSync/issues/1#issuecomment-1752188548_

**Comment by David-Moreira** [comment]
Hey @bleak117

Radarr right? Are you using latest Radarr? I just noticed they added authentication, did you configure it to allow **LAN without authentication**?
Can you check the logs, is the event being processed at all in the app?

**My Connect/Webhook configuration:**
![image](https://github.com/David-Moreira/JellyseerrSync/assets/22283161/6c69ced0-e865-4060-9343-ebc8c869a431)

**By pressing Test in the Connect/Webhook, here's what it should show:**
![image](https://github.com/David-Moreira/JellyseerrSync/assets/22283161/dfba7468-df89-4938-85f4-9e447a82c3cf)

Whenever you receive other events that are setup in the **Radarr Connect Webhook**, you should also get a line logged. If it errors it should also get logged.


You can also try and use radarr logs to see if you find anything there:

http://192.168.1.11:7878/system/events
If something wrong happened you can probably use the **Filter Warn**  to show less logs:
![image](https://github.com/David-Moreira/JellyseerrSync/assets/22283161/13af4bc1-d5e2-47a8-9ba9-920ed5833811)

**Comment by mangurk** [comment]
Where should I be getting this output?
![](https://user-images.githubusercontent.com/22283161/273539271-dfba7468-df89-4938-85f4-9e447a82c3cf.png)

I guess you mean this setting?
<img width="644" alt="Screenshot 2023-10-09 at 7 23 32 a m" src="https://github.com/David-Moreira/JellyseerrSync/assets/135154284/95246fb4-ea43-459e-97f8-ca6b75d85862">

**Comment by David-Moreira** [comment]
> Where should I be getting this output? ![](https://user-images.githubusercontent.com/22283161/273539271-dfba7468-df89-4938-85f4-9e447a82c3cf.png)
> 
> I guess you mean this setting? <img alt="Screenshot 2023-10-09 at 7 23 32 a m" width="644" src="https://user-images.githubusercontent.com/135154284/273598326-95246fb4-ea43-459e-97f8-ca6b75d85862.png">

It should be on your docker logs for that container. 

if you use **Portainer** you can access through here:
![image](https://github.com/David-Moreira/JellyseerrSync/assets/22283161/9c8ba621-9313-4d1a-b2ce-11c9a662cd62)

**Using docker cli:**
**docker ps** to find the container id for the jellyseerr sync container.
**docker logs 15bbe9bf8ed5** => your containerId for the jellyseerr sync container.

**Comment by mangurk** [comment]
Ah yes ok I see the event in the docker logs. I also changed the "Authentication Required" to "Disabled for Local Addresses" which I assume is what you meant. It seems to be working now, actually. I think that might have been the issue.

**Comment by David-Moreira** [comment]
If it tries to process the event successfully you should have a log message like : 

```
Processing Radarr Notification
{The Event from radarr}
Processing MovieFileDelete
```
If it does nothing, the **Processing MovieFileDelete** won't show up.
Example from **Sonarr**, that's similar:
![image](https://github.com/David-Moreira/JellyseerrSync/assets/22283161/3b67d67f-044f-4dde-9c90-95ce8c5f769a)


It it's not working for some reason, post the logs here if you can.

**Comment by mangurk** [comment]
It works! May I suggest a few things? Adding the Authentication Required instruction to the setup guide. Also, perhaps you can add an extra endpoint to check for the success response directly in the browser? Up to you of course :)

**Comment by David-Moreira** [comment]
Sure, I'll take the suggestions.
We can make it a little bit friendlier. It's not a priority as long as it works, so it might take a little longer for me to get to it.

Thanks for the feedback.
