### ISSUE TITLE
Series not found

### ISSUE THREAD

**Issue by ioqy** [David-Moreira/JellyseerrSync#8]
I get the error "Could not find this series: ..." for a series that contains the release year in parparenthesis in the title in sonarr (like "Series Name (2023)").

Why not use the [`/tv/{tvId}`](https://api-docs.overseerr.dev/#/tv/get_tv__tvId_) endpoint of the Jellyseerr API instead of `/search` when the TvdbId is available from the Sonarr notification?

**Comment by David-Moreira** [comment]
Hello @ioqy 
Well I put this together over the course of a day, so I wouldn't be suprised there are bugs or things we can do better.

I believe there was a reason that I can't recall right now why I could not use an endpoint that queries by series Id and had to use search. I think it did not have all the data that I needed?

I will recheck again. Thanks for your feedback.

**Comment by David-Moreira** [comment]
Hello @ioqy 

In the meantime I just noticed that the maintainer of `Jellyseerr`, @Fallenbagel started tackling this issue on the product itself which is great news! 
So I don't think I will allocate further time into this, if we'll have an official solution which will certainly work better then mine. :) 


https://github.com/Fallenbagel/jellyseerr/pull/522

I can however ask, what's the ETA for this much appreciated feature, @Fallenbagel Thanks!!

**Comment by David-Moreira** [comment]
With the release of jellyseer v1.8.0 https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.8.0 a feature was implemented to properly remove media automatically on scan : https://github.com/Fallenbagel/jellyseerr/pull/522
This means that this repository / application should no longer be needed from jellyseerr v1.8.0+. 
This repository will no longer have updates and in a few days it'll be archived. All the docker images will still be available for usage.
Closing issue,
