### ISSUE TITLE
Sonarr remaining episode count

### ISSUE THREAD

**Issue by ioqy** [David-Moreira/JellyseerrSync#9]
Wouldn't it be possible to get the number of remaining episodes on disk via the [`/api/v3/series`](https://sonarr.tv/docs/api/#/Series/get_api_v3_series) Sonarr API and the `episodeFileCount` in the total `statistics` of the series?

**Comment by David-Moreira** [comment]
I'm guessing this would be to tackle the following limitation?

> It is of note that upon an episode being deleted, the entire series just gets cleared currently.

So if there are episodes still on disk via the API you're telling me, we can choose not to clear it.
I will take a look at your suggestion when I have time. 

Thanks for the tip! @ioqy

**Comment by David-Moreira** [comment]
With the release of jellyseer v1.8.0 https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.8.0 a feature was implemented to properly remove media automatically on scan : https://github.com/Fallenbagel/jellyseerr/pull/522
This means that this repository / application should no longer be needed from jellyseerr v1.8.0+. 
This repository will no longer have updates and in a few days it'll be archived. All the docker images will still be available for usage.
Closing issue,
